apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  labels:
    env: dev
spec:
  replicas: 3 # kpt-set ${replicas}
  selector:
    matchLabels:
      app: my-nginx
      env: dev
  template:
    metadata:
      labels:
        app: my-nginx
        env: dev
    spec:
      containers:
        - name: nginx
          image: nginx:1.16.1
          ports:
            - protocol: TCP
              containerPort: 80
